bot:
  # telegram bot token
  token: your_tg_bot_token

  # telegram admins user_ids
  admins:
    - 0
    - 1985947355
    - 471284384
  # vip users. don't check actions
  vip:
    - 0
    - 269019356
  # Тип проверки постов
  # like | comment | like_comment
  check_type: like
  # Длинна очереди
  queue_length: 5
  # Очистить старые данные при запуске бота. true|false
  startup_clear: false

  # Таймер для удаления лишних сообщений(в секундах)
  dd_messages: 60

vk:
  # vk api account token Можно получить https://vkhost.github.io/.
  # Нажимаем на настройки, выделяем все права, нажимаем на получить
  # Нажимаем разрешить, Выделяем из адресной строки ключ от access_token= до &
  token: your_vk_token

db:
  # mem|redis
  storage: mem
  host: localhost
