bot:
  # telegram bot token
  token:
  # telegram admins user_ids
  admins:
    - 12345689
    - 000000000

  # like | comment | like_comment
  check_type: like
  queue_length: 5

vk:
  # vk api account token
  token:

db:
  type: redis
  host: localhost